Added functionality in the docker script to create volumes while running on macOS

diff --git a/docker/yb-voyager-docker b/docker/yb-voyager-docker
--- a/docker/yb-voyager-docker
+++ b/docker/yb-voyager-docker
@@ -1,24 +1,37 @@
-#!/bin/sh
+#!/bin/bash
 
 argv=( "$@" )
 
 if ! which docker > /dev/null; then
-   echo "Could not find docker! Please install docker before proceeeding."
-   exit 1
+	echo "Could not find docker! Please install docker before proceeeding."
+	exit 1
 fi
 
-if [[ $OSTYPE == 'darwin'* ]]; then
-  platform="--platform=linux/amd64"
+if [[ $OSTYPE == 'darwin'* ]]
+then
+	platform="--platform=linux/amd64"
 fi
 
 i=0
 while [ $i -lt $# ]
 do
     if [[ ${argv[${i}]} == "--export-dir" || ${argv[${i}]} == "-e" ]]
-    then
+	then
         j=$(( $i + 1))
-        vol="-v ${argv[$j]}:/export-dir"
-        argv[$j]='/export-dir'
+		export_dir=${argv[${j}]}
+
+		# If the OS is macOS
+		if [[ $OSTYPE == 'darwin'* ]]; then
+
+			# Delete the old volume and create a new one it its place attached to the user's export-dir
+			docker volume rm voyager-export-dir
+			docker volume create --driver local --opt type=none --opt device="${export_dir}" --opt o=bind voyager-export-dir 
+		
+			vol="-v voyager-export-dir:/export-dir"
+		else
+			vol="-v ${export_dir}:/export-dir"
+		fi
+		argv[$j]='/export-dir'
     fi
     i=$(( $i + 1))
 done
