Modified the Dockerfile to install dlv in the built image and made a few modifications to the wrapper script (#720)

diff --git a/docker/yb-voyager-docker b/docker/yb-voyager-docker
--- a/docker/yb-voyager-docker
+++ b/docker/yb-voyager-docker
@@ -2,10 +2,15 @@
 
 argv=( "$@" )
 
+if ! which docker > /dev/null; then
+   echo "Could not find docker! Please install docker before proceeeding."
+   exit 1
+fi
+
 i=0
 while [ $i -lt $# ]
 do
-    if [[ ${argv[${i}]} == "--export-dir" ]]
+    if [[ ${argv[${i}]} == "--export-dir" || ${argv[${i}]} == "-e" ]]
     then
         j=$(( $i + 1))
         vol="-v ${argv[$j]}:/export-dir"
@@ -14,7 +19,7 @@ do
     i=$(( $i + 1))
 done
 
-dockerCmd="docker run ${vol} -it --network=host --rm --privileged yb-voyager yb-voyager ${argv[*]}"
+dockerCmd="docker run ${vol} -it --network=host --rm --privileged yugabytedb/yb-voyager yb-voyager ${argv[*]}"
 
 # echo $dockerCmd
 
