Added check for binutils > 2.25 for CentOS/RHEL/Ubuntu (#296)
* Added check for binutils > 2.25 for CentOS/RHEL/Ubuntu

* Made a few minor changes in install-yb-voyager

* Made changes to check_binutils_version function in install-yb-voyager script

diff --git a/installer_scripts/install-yb-voyager b/installer_scripts/install-yb-voyager
--- a/installer_scripts/install-yb-voyager
+++ b/installer_scripts/install-yb-voyager
@@ -103,6 +103,7 @@ main() {
 
 
 centos_main() {
+	check_binutils_version
 	output "Installing RPM dependencies."
 	$YUM which wget git gcc make 1>&2
 	$YUM perl perl-DBI perl-App-cpanminus 1>&2
@@ -125,6 +126,7 @@ centos_main() {
 
 
 ubuntu_main() {
+	check_binutils_version
 	output "Installing packages."
 	sudo apt update 1>&2
 	sudo apt-get -y install wget  1>&2
@@ -164,6 +166,23 @@ macos_main() {
 #=============================================================================
 # COMMON
 #=============================================================================
+
+check_binutils_version() {
+	output "Checking binutils version."
+	min_required_version='2.25'
+
+	# Example output of "ld -v" on CentOS/RHEL:
+	# GNU ld version 2.30-113.el8
+	# Example output of "ld -v" on Ubuntu:
+	# GNU ld (GNU Binutils for Ubuntu) 2.38
+	version=$(ld -v | awk '{print $NF}' | awk -F '-' '{print $1}')
+
+	if [[ ! "$version" > "$min_required_version" ]] 
+	then
+		echo "ERROR: unsupported binutils version ${version}. Update to binutils version > ${min_required_version} ."
+		exit 1
+	fi
+}
 
 update_yb_voyager_bashrc() {
 	output "Set environment variables in the $RC_FILE ."
