Added a flag for only-pg-support and v/version to the installer script

diff --git a/installer_scripts/install-yb-voyager b/installer_scripts/install-yb-voyager
--- a/installer_scripts/install-yb-voyager
+++ b/installer_scripts/install-yb-voyager
@@ -6,18 +6,36 @@ export LC_ALL=en_US.UTF-8
 
 set -e
 
-VERSION="latest"
-if [ "$1" != "" ]
-then
-	if [ "$1" == "local" ]
-	then
-		# Install from locally checked out branch.
-		VERSION=local
-	else
-		echo "ERROR: Invalid argument: '$1'"
-		exit 1
-	fi
+OPTS=$(getopt -o v: --long version:,only-pg-support -n 'install-yb-voyager' -- "$@")
+
+if [ $? != 0 ]; then 
+	echo "Unable to process the options. Exiting..." >&2; 
+	exit 1; 
 fi
+
+eval set -- "$OPTS"
+
+VERSION="latest"
+ONLY_PG="false"
+
+while true; do
+	case "$1" in
+		-v | --version ) 
+			if [ "$2" == local ]; 
+			then 
+				# Install from locally checked out branch.
+				VERSION="$2"; shift 2;
+			else
+				echo "ERROR: Invalid version"
+				exit 1
+			fi 
+			;;
+		--only-pg-support ) ONLY_PG="true"; shift ;;
+		-- ) shift; break ;;
+		* ) break ;;
+	esac
+done
+
 
 trap on_exit EXIT
 
@@ -108,19 +126,21 @@ centos_main() {
 	check_binutils_version
 	output "Installing RPM dependencies."
 	$YUM which wget git gcc make 1>&2
-	$YUM perl perl-DBI perl-App-cpanminus 1>&2
-	$YUM mysql-devel 1>&2
 	$YUM https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm 1>&2 || true
 	$YUM postgresql14 1>&2
-	$YUM perl-ExtUtils-MakeMaker 1>&2
 
 	install_golang linux
-	centos_install_oracle_instant_clients
-	update_yb_voyager_bashrc
-	install_ora2pg
+	if [ $ONLY_PG == "false" ] ; then
+		$YUM perl perl-DBI perl-App-cpanminus 1>&2
+		$YUM mysql-devel 1>&2
+		$YUM perl-ExtUtils-MakeMaker 1>&2
+		centos_install_oracle_instant_clients
+		update_yb_voyager_bashrc
+		install_ora2pg
+		create_base_ora2pg_conf_file
+	fi
 	install_yb_voyager
 	create_yb_session_vars_file
-	create_base_ora2pg_conf_file
 	update_bashrc
 
 	set +x
@@ -132,20 +152,22 @@ ubuntu_main() {
 	output "Installing packages."
 	sudo apt update 1>&2
 	sudo apt-get -y install wget  1>&2
-	sudo apt-get -y install perl  1>&2
-	sudo apt-get -y install libdbi-perl 1>&2
-	sudo apt-get -y install libaio1 1>&2
-	sudo apt-get -y install cpanminus 1>&2
-	sudo apt-get -y install libmysqlclient-dev 1>&2
 
 	install_golang linux
 	ubuntu_install_postgres
-	ubuntu_install_oracle_instant_clients
-	update_yb_voyager_bashrc
-	install_ora2pg
+	if [ $ONLY_PG == "false" ] ; then
+		sudo apt-get -y install perl  1>&2
+		sudo apt-get -y install libdbi-perl 1>&2
+		sudo apt-get -y install libaio1 1>&2
+		sudo apt-get -y install cpanminus 1>&2
+		sudo apt-get -y install libmysqlclient-dev 1>&2
+		ubuntu_install_oracle_instant_clients
+		update_yb_voyager_bashrc
+		install_ora2pg
+		create_base_ora2pg_conf_file
+	fi
 	install_yb_voyager
 	create_yb_session_vars_file
-	create_base_ora2pg_conf_file
 	update_bashrc
 
 	set +x
