Enhance installer script to setup yb_migrate on mac.
This script doesn't install ora2pg yet. Supports only PG.

diff --git a/installer_scripts/install-yb-voyager b/installer_scripts/install-yb-voyager
--- a/installer_scripts/install-yb-voyager
+++ b/installer_scripts/install-yb-voyager
@@ -16,7 +16,7 @@ LOG_FILE=/tmp/install-yb-voyager.log
 ORA2PG_VERSION="23.1"
 
 # separate file for bashrc related settings
-RC_FILE="$HOME/.yb-voyager.bashrc"
+RC_FILE="$HOME/.yb-voyager.rc"
 touch $RC_FILE
 # just in case last execution of script stopped in between
 source $RC_FILE
@@ -41,8 +41,23 @@ on_exit() {
 main() {
 	set -x
 
-	dist=`cat /etc/os-release | grep -w NAME | awk -F'=' '{print $2}' | tr -d '"'`
+	os=$(uname -s)
+	case ${os} in
+		"Darwin")
+			macos_main
+			exit $?
+			;;
+		"Linux")
+			# Proceed to distribution check.
+			;;
+		*)
+			echo "ERROR: unsupported os ${os}"
+			exit 1
+			;;
+	esac
 
+	# Linux
+	dist=$(cat /etc/os-release | grep -w NAME | awk -F'=' '{print $2}' | tr -d '"')
 	case ${dist} in
 		"CentOS Linux")
 			centos_main
@@ -51,8 +66,9 @@ main() {
 			ubuntu_main
 			;;
 		*)
-			echo "unsupported distribution: ${dist}"
+			echo "ERROR: unsupported linux distribution: ${dist}"
 			exit 1
+			;;
 	esac
 }
 
@@ -66,7 +82,7 @@ centos_main() {
 	$YUM postgresql14-server 1>&2
 	$YUM perl-ExtUtils-MakeMaker 1>&2
 
-	install_golang
+	install_golang linux
 	centos_install_oracle_instant_clients
 	update_yb_migrate_bashrc
 	install_ora2pg
@@ -87,7 +103,7 @@ ubuntu_main() {
 	sudo apt-get -y install cpanminus 1>&2
 	sudo apt-get -y install libmysqlclient-dev 1>&2
 
-	install_golang
+	install_golang linux
 	ubuntu_install_postgres
 	ubuntu_install_oracle_instant_clients
 	update_yb_migrate_bashrc
@@ -98,6 +114,18 @@ ubuntu_main() {
 	set +x
 }
 
+
+macos_main() {
+	output "=================================================="
+	output "NOTE: From MacOS, yb_migrate can only migrate PostgreSQL databases."
+	output "      Use a CentOS/Ubuntu machine to migrate from Oracle/MySQL. "
+	output "=================================================="
+	macos_install_brew
+	macos_install_pg_dump
+	install_golang darwin
+	install_yb_migrate
+	update_bashrc
+}
 
 #=============================================================================
 # COMMON
@@ -144,13 +172,23 @@ install_golang() {
 		output "Found golang."
 		return
 	fi
-	
-	output "Installing golang."
 
-	wget --no-verbose https://golang.org/dl/${GO_VERSION}.linux-amd64.tar.gz 1>&2
+	os=$1
+	arch="$(uname -p)"
+	if [ "${arch}" == "arm" ]
+	then
+		arch="arm64"
+	else
+		arch="amd64"
+	fi
+
+	file_name="${GO_VERSION}.${os}-${arch}.tar.gz"
+	output "Installing golang os=${os} arch=${arch}."
+
+	wget --no-verbose https://golang.org/dl/${file_name} 1>&2
 	rm -rf $GOROOT
-	tar -C /tmp -xzf ${GO_VERSION}.linux-amd64.tar.gz 1>&2
-	rm ${GO_VERSION}.linux-amd64.tar.gz
+	tar -C /tmp -xzf ${file_name} 1>&2
+	rm ${file_name}
 }
 
 
@@ -213,22 +251,25 @@ install_ora2pg() {
 
 
 update_bashrc() {
+	# Either ${HOME}/.bashrc or ${HOME}/.zshrc .
+	rc_file_name="${HOME}/.$(basename $(echo $SHELL))rc"
+
 	line="source $RC_FILE"
-	if grep -qxF "$line" $HOME/.bashrc
+	if grep -qxF "$line" ${rc_file_name}
 	then
-		output "No need to update bashrc again."
+		output "No need to update ${rc_file_name} again."
 		return
 	fi
 	while true; do
 		printf "\n*** File - $RC_FILE contents ***\n\n"
 		cat $RC_FILE
 
-		printf "\n\nAdd $RC_FILE to $HOME/.bashrc file (Y/N)? "
+		printf "\n\nAdd $RC_FILE to ${rc_file_name} file (Y/N)? "
 		read yn
 		case $yn in
 		[Yy]* )
-			grep -qxF "$line" $HOME/.bashrc || echo $line >> $HOME/.bashrc
-			echo "execute: \"source $HOME/.bashrc\" before continuing in same shell"
+			grep -qxF "$line" ${rc_file_name} || echo $line >> ${rc_file_name}
+			echo "execute: \"source ${rc_file_name}\" before continuing in same shell"
 			break;;
 		[Nn]* )
 			echo "execute: \"source $RC_FILE\" before continuing to have paths set in current shell"
@@ -289,5 +330,32 @@ ubuntu_install_oic() {
 		rm ${rpm_name}
 	fi
 }
+
+#=============================================================================
+# MacOS
+#=============================================================================
+
+macos_install_brew() {
+	which brew > /dev/null 2>&1
+	if [ $? -eq 0 ]
+	then
+		output "brew is already installed."
+	else
+		output "Installing brew."
+		set +x  # Do not dump the brew install.sh into the log.
+		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+		set -x
+	fi
+}
+
+macos_install_pg_dump() {
+	output "Installing pg_dump and pg_restore."
+	brew install libpq
+	insert_into_rc_file 'export PATH="/opt/homebrew/opt/libpq/bin:$PATH"'
+}
+
+#=============================================================================
+# Start.
+#=============================================================================
 
 main 2>> $LOG_FILE
