Made the suggested changes

diff --git a/installer_scripts/install-yb-voyager b/installer_scripts/install-yb-voyager
--- a/installer_scripts/install-yb-voyager
+++ b/installer_scripts/install-yb-voyager
@@ -184,29 +184,25 @@ macos_main() {
 #=============================================================================
 
 check_java() {
-		if [ -z "$JAVA_HOME" ]; then
-			JAVA_BINARY="java"
-		else
-			JAVA_BINARY="$JAVA_HOME/bin/java"
-		fi
-
-        MIN_REQUIRED_MAJOR_VERSION='11'
-		JAVA_MAJOR_VER=$(${JAVA_BINARY} -version 2>&1 | awk -F '"' '/version/ {print $2}' | awk -F. '{print $1}')
-		
-        if ([ -n "$JAVA_MAJOR_VER" ] && (( 10#${JAVA_MAJOR_VER} >= 10#${MIN_REQUIRED_MAJOR_VERSION} )) ) #integer compare of versions.
-        then
-        	output "Found sufficient java version = ${JAVA_MAJOR_VER}"
-        else
-        	output "ERROR: Java not found or insuffiencient version ${JAVA_MAJOR_VER}. Please install java>=${MIN_REQUIRED_MAJOR_VERSION}"
-			exit 1;
-        fi
+	if [ -z "$JAVA_HOME" ]; then
+		JAVA_BINARY="java"
+	else
+		JAVA_BINARY="$JAVA_HOME/bin/java"
+	fi
+	
+	if which "${JAVA_BINARY}" >/dev/null 2>&1; then
+    	echo "Found Java."
+	else
+    	echo "Java not found."
+		exit 1
+	fi
 }
 
 install_debezium_server() {
 	output "Installing debezium"
 	debezium_server_filename="debezium-server-${DEBEZIUM_TARBALL_VERSION}.tar.gz"
 	# download
-	wget -nv "https://github.com/yugabyte/debezium/releases/download/voyager-debezium/${debezium_server_filename}"
+	wget -nv "https://github.com/yugabyte/debezium/releases/download/voyager-debezium-${DEBEZIUM_TARBALL_VERSION}/${debezium_server_filename}"
 	# move to /opt/yb-voyager/debezium-server
 	sudo tar -xzf ${debezium_server_filename} -C /opt/yb-voyager 1>&2
 	# cleanup
